apiVersion: apps/v1
kind: Deployment
metadata:
  name: inject-deployment
  namespace: istio-study
  labels:
    app: inject-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: inject-app
  template:
    metadata:
      labels:
        app: inject-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.14-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80