apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-gateway
spec:
  selector: 
    app: istio-ingressgateway
  servers:
    - port:
        number: 80
        name: web-http
        targetPort: 8080
        protocol: TCP
      hosts:
        - "*"